### ISSUE TITLE
Support insecure registries in non-daemon case

### ISSUE THREAD

**Issue by jromero** [buildpacks/lifecycle#524] opened 2021-02-09 22:09 UTC
## Summary

As a developer, I'd like to be able to publish app images to an "insecure" registry in the non-daemon case.

_(NOTE: I mention non-daemon case because the daemon case is controlled/configured via Docker Desktop.)_

Currently, this partly works in some local setups because [GGCR attempts to detect protocol](https://sourcegraph.com/github.com/google/go-containerregistry@51f01e739161bf35d663240a8ca404777d7d9378/-/blob/pkg/name/registry.go#L75-95).

In my current development environment, it doesn't work because I'm routing to the registry from inside a container and thereby referencing it as [`host.docker.internal`](https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds) which doesn't match GGCR's logic.

A potential solution may be to go to GGCR and request that `host.docker.internal` be added to their detection logic BUT it seems like this may be desirable in other scenarios. (See [prior art](#prior-art)).

## Proposed Solution

Since there are multiple images at play sometimes, instead of a single global flag `--insecure` (like kaniko) add a variadic flag + matching character separated env var for insecure registries.

For example:

```bash
analyzer --insecure-registry=my-registry.com/here/  --insecure-registry=host.docker.internal
```

```bash
CNB_INSECURE_REGISTRIES="my-registry.com/here/;host.docker.internal"
analyzer ...
```

### Prior Art

- [kaniko](https://github.com/GoogleContainerTools/kaniko#--insecure)
- [crane](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane_pull.md#options-inherited-from-parent-commands)

**Comment by jabrown85** [comment] 2021-02-11 16:59
Discussion on Feb 11 - Attendees agree and an RFC will be produced to capture details.

**Comment by jromero** [comment] 2021-06-17 14:34
Another platform specific use case (Tekton) where this feature would be useful: https://github.com/buildpacks/tekton-integration/issues/31#issue-923993266

**Comment by wanjunlei** [comment] 2022-08-08 00:40
Any progress on this? Or is there a definite plan? Is there anything I can do?

**Comment by natalieparellano** [comment] 2022-08-09 15:55
Thank you, @wanjunlei - at this point, I believe what we'd need to move forward is an [RFC](https://github.com/buildpacks/rfcs) defining the user interface to the lifecycle (it could build off of @jromero's proposal above or be something different). Would you be interested in helping with that? If so, I'd be happy to help guide you through the process. You can find me as narellano in [CNCF Slack](slack.cncf.io) for real-time conversation.

**Comment by wanjunlei** [comment] 2022-08-18 06:29
I had created an RFC  buildpacks/rfcs#229 @natalieparellano .

**Comment by wanjunlei** [comment] 2022-12-06 03:35
Hi @natalieparellano , the RFC had merged, what do I need to do next, start coding or update the platform API?

**Comment by jjbustamante** [comment] 2022-12-06 13:52
Hi @wanjunlei, the final implementation requires several updates in different repositories. the following `tracking` [issue](https://github.com/buildpacks/rfcs/issues/246) was created to follow up that work.

The issues there are marked as **to be done**, so in my opinion you can start working on the lifecycle implementation, later we can work on creating and filling the issues on the other repositories. Also, you can create a draft PR in the spec repository and start collecting feedback there, once the issue is created in the spec repo you can link the PR to it.

**Comment by wanjunlei** [comment] 2022-12-07 06:04
> Hi @wanjunlei, the final implementation requires several updates in different repositories. the following `tracking` [issue](https://github.com/buildpacks/rfcs/issues/246) was created to follow up that work.
> 
> The issues there are marked as **to be done**, so in my opinion you can start working on the lifecycle implementation, later we can work on creating and filling the issues on the other repositories. Also, you can create a draft PR in the spec repository and start collecting feedback there, once the issue is created in the spec repo you can link the PR to it.

OK, I will start working on the lifecycle implementation first.

**Comment by natalieparellano** [comment] 2024-02-08 17:53
I'm going to close this one out as https://github.com/buildpacks/lifecycle/issues/1287 will likely add 0.13 to the list of supported Platform APIs.

**Closed by natalieparellano** 2024-02-08 17:53 UTC
Labels: type/enhancement, status/ready
