### ISSUE TITLE
"pack build --publish" to Github Package Registry fails during export

### ISSUE THREAD

**Issue by making** [buildpacks/lifecycle#323] opened 2019-11-01 08:32 UTC
`pack build --publish` to [Github Package Registry](https://help.github.com/en/github/managing-packages-with-github-package-registry/configuring-docker-for-use-with-github-package-registry) fails in ANALYZING phase with the following message. Tested with `v0.5.0 (git sha: c9cfac75b49609524e1ea33f809c12071406547c)`

```
===> ANALYZING
[analyzer] Error: failed to access previous image: connect to repo store 'docker.pkg.github.com/<owner>/<repo>/<image>:latest': NAME_UNKNOWN: docker package "<image>" does not exist under owner "<image>/<repo>"
ERROR: failed with status code: 1
```

Actually it works without `--publish` option + `docker push`.

**Comment by jromero** [comment] 2020-06-24 20:53
Verified by @dfreilich. This is likely to require a change to `imgutil` and a new version of `lifecycle`.

@ekcasey / @natalieparellano  correct me if I'm wrong.

**Comment by khaledavarteq** [comment] 2020-06-29 18:50
I've had a very similar issue with a GitHub docker registry whereas the same exporter step in a Tekton taskrun worked with an ECR registry instance. So it seems to be tied to GitHub registries.

**Comment by ekcasey** [comment] 2020-06-30 16:38
There are two issues here:

**Analyze**
The analyzer issue was already fixed in lifecycle v0.8.0 (we added more permissive error in `imgutil` to catch a wider range of repo not found errors coming from different registries) - https://github.com/buildpacks/lifecycle/issues/303

**Export**
The problems exporting to the github package registry are caused by this issue - https://github.community/t/cannot-pull-docker-image-from-github-package-registry-by-digest/14342

The github registry doesn't support fetching manifests by digest. We explicitly record the digest of the previous image during `analyze` and use the digest reference when reusing layers in export (this helps avoid race conditions and other errors). The lack of support for digest reference makes the github package registry uncompliant with the [OCI Distribution spec](https://github.com/opencontainers/distribution-spec/blob/master/spec.md#pulling-an-image-manifest).

We could try to do something special to support the github package registry despite it's non-compliance:
1. Always use tag reference and double check the digest when reading. This creates potential failure scenarios that don't exist for other registries (the build will fail if the tag has been updated between the analyze and export phases).
2. Never fetch the manifest during export (save everything we need during analyze). No race conditions here, but this would require massive changes and still has some limitations (you wouldn't be able to give `analyzer` a digest reference, which the lifecycle supports generally).

I would prefer that github simply add support for digest references... not sure how realistic that it on a reasonable time table.
IMHO a registry that doesn't support content-addressable images is not a registry worth using

**Comment by dfreilich** [comment] 2020-08-05 00:45
Apparently GH Registry is opening a private beta with support for fetching manifests by digest (see https://github.com/containerd/containerd/issues/3291#issuecomment-640253502 for details). Hopefully they'll roll that out and we'll be able to close this.

**Comment by dfreilich** [comment] 2020-09-01 18:27
With the release of Github Container Registry (https://github.blog/2020-09-01-introducing-github-container-registry/), I was successfully able to publish an image with `pack`. 

```
$ pack build ghcr.io/dfreilich/goflake-server:latest --publish
...
===> EXPORTING
Reusing layers from image 'ghcr.io/dfreilich/goflake-server@sha256:5cc11b3794216aa23e3b1fad52994ccfb34fb52309e99ec96aebba57193294c3'
Reusing layer 'paketo-buildpacks/go-build:targets'
Reusing 1/1 app layer(s)
Reusing layer 'launcher'
Reusing layer 'config'
Adding label 'io.buildpacks.lifecycle.metadata'
Adding label 'io.buildpacks.build.metadata'
Adding label 'io.buildpacks.project.metadata'
*** Images (sha256:5cc11b3794216aa23e3b1fad52994ccfb34fb52309e99ec96aebba57193294c3):
      ghcr.io/dfreilich/goflake-server:latest
Reusing cache layer 'paketo-buildpacks/go-dist:go'
Reusing cache layer 'paketo-buildpacks/go-build:gocache'
Successfully built image ghcr.io/dfreilich/goflake-server:latest
```

This issue can be closed.

**Closed** 2020-09-01 18:47 UTC
Labels: status/ready, type/bug
