### ISSUE TITLE
stat /root/.docker/config.json: permission denied

### ISSUE THREAD

**Issue by jromero** [buildpacks/lifecycle#290] opened 2020-05-08 09:46 UTC
### Summary
Confusing error when docker credentials are not passed to lifecycle.

---

##### Steps

1. `git clone https://github.com/buildpacks/samples`
2. `cd apps/java-maven/`
3. run pack build while setting $HOME to a directory that doesn't contain `.docker/config.json`. This would simulate `pack` not being able to find `$HOME/.docker/config.json` to pass to the lifecycle.
```bash
HOME=/tmp/ pack build jromeropivot/sample-app --builder cloudfoundry/cnb:bionic --publish
```

##### Current behavior

From the little I looked into it, the error originates from the fact that in the happy path `pack` passes `CNB_REGISTRY_AUTH` and if the creds are found there everything is good. If it doesn't, or `pack` doesn't pass `CNB_REGISTRY_AUTH` then the current implementation fallsback to `$HOME/.docker/config.json` within the container. From the looks of it the executing user then has no access to read from it's $HOME???

```
bionic: Pulling from cloudfoundry/cnb
Digest: sha256:1675aee1ecf365dca987fb37d65ee1acd8bc6b859cbcefd9ab0aa870067cf77d
Status: Image is up to date for cloudfoundry/cnb:bionic
===> DETECTING
[detector] 6 of 15 buildpacks participating
[detector] paketo-buildpacks/bellsoft-liberica 2.5.2
[detector] paketo-buildpacks/maven             1.2.1
[detector] paketo-buildpacks/executable-jar    1.2.2
[detector] paketo-buildpacks/apache-tomcat     1.1.2
[detector] paketo-buildpacks/dist-zip          1.2.2
[detector] paketo-buildpacks/spring-boot       1.5.2
===> ANALYZING
[analyzer] ERROR: failed to get previous image: /root/.docker/config.json: stat /root/.docker/config.json: permission denied
ERROR: failed with status code: 1
```

##### Expected

I would expect an error that points me to the fact that the credentials for `index.docker.io` were not found (aka authentication error). 

---

##### lifecycle version / platform version(s)
```
Lifecycle:
  Version: 0.7.4
  Buildpack API: 0.2
  Platform API: 0.3
```

**Comment by ekcasey** [comment] 2020-05-08 14:03
This is likely caused by recent changes we made (no longer looking up the user and setting `HOME` and `DOCKER_CONFIG` when we run as analyzer/exporter as root and then drop privileges). The problem is that, assuming we can/should set those variables is the "wrong" thing to do when we run in platforms like `tekton` that are configuring auth by overriding those vars explicitly.

I wonder if that right solution here is to make `pack` more like other platforms and pass auth by copying a docker `config.json` into the container and setting `DOCKER_CONFIG` instead of setting `CNB_REGISTRY_AUTH`.

Other solutions (not mutually exclusive with the above solution):
1. don't run analyze/exporter as `root` in `pack` w/ `--publish` (this isn't necessary in other platforms but currently exists in `pack` to avoid problems with volume ownership that are solved by other means (`securityContext.fsGroup` -`kpack`, a prepare step that `chown`s volumes -`tekton`) in other platforms
2. in lifecycle - don't fall back on the docker config.json if CNB_REGISTRY_AUTH is provided ( nobody does this except for `pack` anyways and there is never a real `config.json` in that case
3. in lifecycle - resolve all auths before changing users (bonus, we could test for write permissions earlier in `export`)

**Comment by jromero** [comment] 2020-05-08 20:11
I feel torn between `CNB_REGISTRY_AUTH` and the `.docker/config.json`. It would be nice to have a more idiomatic method to provide authentication but it does seem that at least for now the standard is to use `.docker/config.json` on just about any OCI related system. I would be in favor of pack making the switch in the interim.

**Comment by ekcasey** [comment] 2020-05-08 22:32
@natalieparellano and I decided #292 is a good quick fix for now.

We can address how to do the more idiomatic thing safely in the future. Allowing the lifecycle while preventing buildpacks from reading the registry creds from a docker `config.json` on disk will require some care in the `creator` case.

**Comment by ekcasey** [comment] 2020-05-08 22:33
Closing b/c #292 resolves the immediate issue

**Closed by ekcasey** 2020-05-08 22:33 UTC
Labels: status/triage, type/bug
