### ISSUE TITLE
Failed to export: get run image top layer SHA: image XXXXXX has no layers

### ISSUE THREAD

**Issue by xiujuan95** [buildpacks/lifecycle#338] opened 2020-07-19 05:50 UTC
### Summary

At `export` step, it failed because get run-image top layer failed:
```
$ /cnb/lifecycle/exporter -app=/workspace/source -layers=/layers -cache-dir=/workspace/cache -group=/layers/group.toml icr.io/obs/codeengine/buildpacks/paketo-example
Warning: Warning: analyzed TOML file not found at './analyzed.toml'
no stack metadata found at path '/cnb/stack.toml', stack metadata will not be exported
ERROR: failed to export: get run image top layer SHA: image icr.io/obs/codeengine/buildpacks/paketo-example has no layers
```

I build my own run-image and push it to registry. 

I open this issue is to ask you guys, when will above issue happen? Or under what situations will cause this issue? Pls provide some suggestions  for me, thanks a lot!

I have verified, within builder image, credential which is used to pull run-image exists.
```
$ cd .docker
$ pwd
/home/cnb/.docker
$ ls
config.json
$ cat config.json
{
        "auths": {
                "icr.io": {
                        "auth": "aaaaaaaaa",
                        "identitytoken": "bbbbbbbbbb"
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/19.03.6 (linux)"
        }
}
```
---

##### Steps

1.
2.
3.

##### Expected

---

**Comment by xiujuan95** [comment] 2020-07-20 06:50
I think I have found the root cause is I don't have authorization to pull run-image. 

So this causes another question, whether you support put run-image to a private registry and the account of this registry is different from push image account? 

To be more clear, I will provide an example in below:
1.  run-image locate in `icr.io/obs/buildpack/run-image` ;
2.  I want to push my app-image to `icr.io/obs/coligo;

`1` and `2` have the same registry endpoint, but they are different accounts, so I can't write `.docker/config.json` file like below (because same key doesn't be allowed in json format):
```
{
        "auths": {
                "icr.io": {
                        "auth": "xxxxxxxx",
                        "identitytoken": "aaaaaaaaaaa"
                },
               "icr.io": {
                        "auth": "xxxxxxxxx",
                        "identitytoken": "bbbbbbbbb"
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/19.03.6 (linux)"
        }
}
```
So for this situation, I don't know whether there exist other workarounds can fix above issue or not? 
Or whether above situation is supported or not?

Besides, I did an experiment, `docker run` into the builder image with root role and then `docker login` registry, and then run `/cnb/lifecycle/exporter` command, look like it only fetches run-image, but it can't push image:
```
cnb@2567bbe72797:/$ /cnb/lifecycle/exporter -app=/workspace/source -layers=/layers -cache-dir=/workspace/cache -group=/layers/group.toml icr.io/obs/coligo
Warning: Warning: analyzed TOML file not found at './analyzed.toml'
Adding layer 'launcher'
Adding layer 'paketo-buildpacks/node-engine:node'
Adding layer 'paketo-buildpacks/npm:modules'
Adding 1/1 app layer(s)
Adding layer 'config'
*** Images (sha256:8b7921363721d56b668a82336406a1234c516c6c9de6e26d3e1a9f3105a70616):
      icr.io/obs/coligo - POST https://icr.io/v2/obs/coligo/blobs/uploads/?from=obs%2Fcodeengine%2Fbuildpacks%2Fubi-stack-run&mount=sha256%3Ae4008a20f43bfb6732dc4f8a35ed15023e8c1d352fd521b2e37a34a916e87fd1: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:obs/coligo Type:repository] map[Action:push Class: Name:obs/coligo Type:repository] map[Action:pull Class: Name:obs/codeengine/buildpacks/ubi-stack-run Type:repository]]
ERROR: failed to export: failed to write image to the following tags: [icr.io/obs/coligo: POST https://icr.io/v2/obs/coligo/blobs/uploads/?from=obs%2Fcodeengine%2Fbuildpacks%2Fubi-stack-run&mount=sha256%3Ae4008a20f43bfb6732dc4f8a35ed15023e8c1d352fd521b2e37a34a916e87fd1: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:obs/coligo Type:repository] map[Action:push Class: Name:obs/coligo Type:repository] map[Action:pull Class: Name:obs/codeengine/buildpacks/ubi-stack-run Type:repository]]]
```

**Comment by ekcasey** [comment] 2020-07-20 15:24
Hi @xiujuan95 thank you for the question. In general we do not support to authenticating as two different users against the same registry. A user that is exporting an app image is expected to have read access to the run-image repo and write access to the app image repo.

The general theory is that the user or client should have a single identity and that identity should be granted the appropriate level of access to all of the relevant resources. This assumption is built into a lot of the lower level tooling we use (as you highlighted when you described the issue adding both identities to a docker `config.json` file). In general I think CNB should work within those assumption unless there is a really compelling reason not to.

Are you comfortable sharing more about your use case? Why can't the user be granted read access to the run-image?

**Comment by xiujuan95** [comment] 2020-07-21 01:59
@ekcasey Sure, thanks for your kind reply! 
My scenario is I build my own build-image, run-image and push them to my private registry. And then based on tekton-pipeline and set up a taskRun to build my source code. This taskRun is consuming my own build-image and run-image. Also I want to push my app-image to above private registry, but it has a different account from run-image and build-image location. So above issue happens.
So maybe I need to write my secret to the builder image first.

**Comment by dfreilich** [comment] 2020-08-10 17:20
Hey @xiujuan95 ! Seems like the issue is resolved, so I'll close it, but feel free to reopen if you need any more support.

**Closed** 2020-08-10 17:32 UTC
Labels: status/triage, type/bug
